### ISSUE TITLE
Unknown CPI Error 'Invalid Call'

### ISSUE THREAD

**Issue by K7king** [cloudfoundry-incubator/service-fabrik-blueprint-boshrelease#9]
I tried to deploy service-fabrik blueprint bosh release as an experiment . I changed the Bosh Director UUID and while I deploy getting the following error "Unknown CPI error 'InvalidCall' with message 'Arguments are not correct, details: 'expected params[:filters][0][:values][0] to be a String, got value nil (class: NilClass) instead.'' in 'create_vm' CPI method"

Can you please assist on configuring the yml file to deploy.

**Comment by ashishjain14** [comment]
Can you share the manifest file? Please share more details on the target environment.

**Comment by K7king** [comment]
name: blueprint
director_uuid: b57fcd70-2785-4708-b337-560f8538b2a

releases:
- name: blueprint
  version: latest

compilation:
  workers: 1
  network: blueprint-network
  reuse_compilation_vms: true
  cloud_properties:
    name: random

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

resource_pools:
- name: default
  network: blueprint-network
  size: 1
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    name: random

networks:
- name: blueprint-network
  type: manual
  subnets:
  - range: 10.244.3.0/30
    gateway: 10.244.3.1
    static:
      - 10.244.3.2
    cloud_properties:
      name: random
  - range: 10.244.3.4/30
    gateway: 10.244.3.5
    static: []
    cloud_properties:
      name: random

jobs: &jobs
- name: blueprint
  templates:
  - { name: blueprint }
  - { name: blueprint-agent }
  instances: 1
  persistent_disk: 1024
  resource_pool: default
  networks:
    - name: blueprint-network
      static_ips:
        - 10.244.3.2

properties:
  blueprint: &blueprint
    port: 8080
    admin:
      username: admin
      password: admin
  agent:
    port: 2718
    username: admin
    password: admin
    provider:
      name: boshlite
      container: blueprint_backup
    manifest:
      jobs: *jobs
      properties:
        blueprint: *blueprint


Target Environment :AWS

**Comment by ashishjain14** [comment]
[sample-aws-manifest.yml.txt](https://github.com/SAP/service-fabrik-blueprint-boshrelease/files/1471027/sample-aws-manifest.yml.txt)
Attached a sample manifest, please fill in the sections marked as xxxxx, mainly around 
1. availability_zone
2. security_groups
3. subnet
4. static(static ip address for the instance)
5. range
6. gateway
7. reserved(reserved ip address)
8. access_key_id
9. container
10. region_name
11. secret_access_key

let us know how it goes.
